# We need a newer version of CMake than is installed on Ubuntu 12.04
# Therefore request to use Ubuntu 14.04 instead
dist: trusty
sudo: false

language: c

compiler: gcc

# N.B. `gfortran` is not allowed but `gfortran-4.8` is ?!?
addons:
  apt:
    packages:
    - cmake
    - gfortran-4.8

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
    - ctest
